// examples/svelte-ts/src/lib/components/connect.svelte
<script lang="ts">
  import * as ed from '@noble/ed25519'
  import {
    ScopeType,
    SignDataError,
    useWallet,
    WalletId,
    type Siwa,
    type Wallet
  } from '@txnlab/use-wallet-svelte'
  import algosdk from 'algosdk'
  import { canonify } from 'canonify'
  import { onDestroy } from 'svelte'
  import {
    isFirebaseConfigured,
    firebaseSignOut,
    getFreshIdToken,
    onFirebaseAuthStateChanged,
    type User
  } from '$lib/firebase'
  import FirebaseAuth from './FirebaseAuth.svelte'

  const props = $props()
  const { activeAddress, algodClient, signData, transactionSigner } = useWallet()
  const wallet: Wallet = props.wallet

  // Firebase auth state
  let firebaseUser = $state<User | null>(null)

  // Subscribe to Firebase auth state
  const unsubscribe = onFirebaseAuthStateChanged((user) => {
    firebaseUser = user
  })
  onDestroy(() => unsubscribe())

  const setActiveAccount = (event: Event, wallet: Wallet) => {
    const target = event.target as HTMLSelectElement
    wallet.setActiveAccount(target.value)
  }

  let magicEmail = $state('')
  const isMagicLink = () => wallet.id === WalletId.MAGIC
  const isWeb3Auth = () => wallet.id === WalletId.WEB3AUTH
  const isEmailValid = () => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(magicEmail)

  const isConnectDisabled = () => {
    if (wallet.isConnected()) {
      return true
    }
    if (isMagicLink() && !isEmailValid()) {
      return true
    }
    return false
  }

  // Firebase SFA connection
  async function handleFirebaseConnect() {
    if (!firebaseUser) {
      console.error('[App] No Firebase user signed in')
      return
    }

    const idToken = await getFreshIdToken()
    if (!idToken) {
      console.error('[App] Failed to get Firebase ID token')
      return
    }

    const verifierId = firebaseUser.uid
    console.info('[App] Connecting Web3Auth with Firebase auth...', { verifierId })

    await wallet.connect({ idToken, verifierId })
  }

  async function handleConnect() {
    if (isMagicLink()) {
      await wallet.connect({ email: magicEmail })
    } else {
      await wallet.connect()
    }
  }

  async function handleFirebaseSignOut() {
    try {
      await firebaseSignOut()
      console.info('[App] Signed out from Firebase')
    } catch (error) {
      console.error('[App] Firebase sign-out error:', error)
    }
  }

  let isSending = $state(false)
  async function sendTransaction() {
    try {
      const sender = activeAddress.current
      if (!sender) {
        throw new Error('[App] No active account')
      }

      const atc = new algosdk.AtomicTransactionComposer()
      const suggestedParams = await algodClient.current.getTransactionParams().do()

      const transaction = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
        sender: sender,
        receiver: sender,
        amount: 0,
        suggestedParams
      })

      atc.addTransaction({ txn: transaction, signer: transactionSigner })

      console.info(`[App] Sending transaction...`, transaction)

      isSending = true

      const result = await atc.execute(algodClient.current, 4)

      console.info(`[App] ✅ Successfully sent transaction!`, {
        confirmedRound: result.confirmedRound,
        txIDs: result.txIDs
      })
    } catch (error) {
      console.error('[App] Error signing transaction:', error)
    } finally {
      isSending = false
    }
  }
  async function auth() {
    const activeAddr = activeAddress.current
    if (!activeAddr) {
      throw new Error('[App] No active account')
    }
    try {
      const siwaRequest: Siwa = {
        domain: location.host,
        chain_id: '283',
        account_address: activeAddr,
        type: 'ed25519',
        uri: location.origin,
        version: '1',
        'issued-at': new Date().toISOString()
      }
      const dataString = canonify(siwaRequest)
      if (!dataString) throw Error('Invalid JSON')
      const data = btoa(dataString)
      const metadata = { scope: ScopeType.AUTH, encoding: 'base64' }
      const resp = await signData(data, metadata)
      // verify signature
      const enc = new TextEncoder()
      const clientDataJsonHash = await crypto.subtle.digest('SHA-256', enc.encode(dataString))
      const authenticatorDataHash = await crypto.subtle.digest('SHA-256', new Uint8Array(resp.authenticatorData))
      const toSign = new Uint8Array(64)
      toSign.set(new Uint8Array(clientDataJsonHash), 0)
      toSign.set(new Uint8Array(authenticatorDataHash), 32)
      const pubKey = algosdk.Address.fromString(activeAddr).publicKey
      if (!(await ed.verifyAsync(resp.signature, toSign, pubKey))) {
        throw new SignDataError('Verification Failed', 4300)
      }
      console.info(`[App] ✅ Successfully authenticated!`)
    } catch (error) {
      console.error('[App] Error signing data:', error)
    }
  }
</script>

<div class="wallet-group">
  <h4>
    {wallet.metadata.name}
    {#if wallet.isActive()}<span>[active]</span>{/if}
  </h4>
  <div class="wallet-buttons">
    <button onclick={handleConnect} disabled={isConnectDisabled()}>
      Connect
    </button>
    <button onclick={wallet.disconnect} disabled={!wallet.isConnected()}> Disconnect </button>
    {#if !wallet.isActive()}
      <button onclick={wallet.setActive} disabled={!wallet.isConnected() || wallet.isActive()}>
        Set Active
      </button>
    {:else}
      <button onclick={sendTransaction} disabled={isSending}>
        {isSending ? 'Sending Transaction...' : 'Send Transaction'}
      </button>
      {#if wallet.canSignData}
        <button onclick={auth}>Authenticate</button>
      {/if}
    {/if}
  </div>
  {#if isMagicLink()}
    <div class="input-group">
      <label for="magic-email">Email:</label>
      <input
        id="magic-email"
        type="email"
        bind:value={magicEmail}
        placeholder="Enter email to connect..."
        disabled={wallet.isConnected()}
      />
    </div>
  {/if}
  <!-- Firebase SFA Authentication -->
  {#if isWeb3Auth() && isFirebaseConfigured && !wallet.isConnected()}
    <div class="firebase-sfa-section">
      <div class="section-divider">
        <span>or connect with Firebase</span>
      </div>
      {#if firebaseUser}
        <div class="firebase-user">
          <span>Signed in as: {firebaseUser.email || firebaseUser.uid}</span>
          <div class="firebase-user-buttons">
            <button type="button" onclick={handleFirebaseSignOut}>
              Sign Out
            </button>
            <button type="button" onclick={handleFirebaseConnect}>
              Connect with Firebase
            </button>
          </div>
        </div>
      {:else}
        <div class="firebase-auth">
          <FirebaseAuth onSignInSuccess={() => console.info('[App] Firebase sign-in successful')} />
        </div>
      {/if}
    </div>
  {/if}
  <!-- End Firebase SFA Authentication -->
  {#if wallet.isActive() && wallet.accounts.current?.length}
    <div>
      <select value={activeAddress.current} onchange={(event) => setActiveAccount(event, wallet)}>
        {#each wallet.accounts.current as account}
          <option>
            {account.address}
          </option>
        {/each}
      </select>
    </div>
  {/if}
</div>

// examples/nextjs/src/app/Connect.tsx
'use client'

import * as ed from '@noble/ed25519'
import {
  NetworkId,
  ScopeType,
  SignDataError,
  Siwa,
  WalletId,
  useNetwork,
  useWallet,
  type Wallet
} from '@txnlab/use-wallet-react'
import algosdk from 'algosdk'
import { canonify } from 'canonify'
import * as React from 'react'
import {
  isFirebaseConfigured,
  firebaseSignOut,
  getFreshIdToken,
  onFirebaseAuthStateChanged,
  type User
} from './firebase'
import { FirebaseAuth } from './FirebaseAuth'
import styles from './Connect.module.css'

export function Connect() {
  const { algodClient, activeAddress, signData, transactionSigner, wallets } = useWallet()
  const { activeNetwork, setActiveNetwork } = useNetwork()

  const [isSending, setIsSending] = React.useState(false)
  const [magicEmail, setMagicEmail] = React.useState('')

  // Firebase auth state
  const [firebaseUser, setFirebaseUser] = React.useState<User | null>(null)

  // Subscribe to Firebase auth state changes
  React.useEffect(() => {
    const unsubscribe = onFirebaseAuthStateChanged((user) => {
      setFirebaseUser(user)
    })
    return unsubscribe
  }, [])

  const isMagicLink = (wallet: Wallet) => wallet.id === WalletId.MAGIC
  const isWeb3Auth = (wallet: Wallet) => wallet.id === WalletId.WEB3AUTH
  const isEmailValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(magicEmail)

  const isConnectDisabled = (wallet: Wallet) => {
    if (wallet.isConnected) {
      return true
    }
    if (isMagicLink(wallet) && !isEmailValid) {
      return true
    }
    return false
  }

  // Firebase SFA connection
  const handleFirebaseConnect = async (wallet: Wallet) => {
    if (!firebaseUser) {
      console.error('[App] No Firebase user signed in')
      return
    }

    const idToken = await getFreshIdToken()
    if (!idToken) {
      console.error('[App] Failed to get Firebase ID token')
      return
    }

    const verifierId = firebaseUser.uid
    console.info('[App] Connecting Web3Auth with Firebase auth...', { verifierId })

    await wallet.connect({
      idToken,
      verifierId
    })
  }

  const handleConnect = async (wallet: Wallet) => {
    if (isMagicLink(wallet)) {
      await wallet.connect({ email: magicEmail })
    } else {
      await wallet.connect()
    }
  }

  const handleFirebaseSignOut = async () => {
    try {
      await firebaseSignOut()
      console.info('[App] Signed out from Firebase')
    } catch (error) {
      console.error('[App] Firebase sign-out error:', error)
    }
  }

  const setActiveAccount = (event: React.ChangeEvent<HTMLSelectElement>, wallet: Wallet) => {
    const target = event.target
    wallet.setActiveAccount(target.value)
  }

  const sendTransaction = async () => {
    try {
      if (!activeAddress) {
        throw new Error('[App] No active account')
      }

      const atc = new algosdk.AtomicTransactionComposer()
      const suggestedParams = await algodClient.getTransactionParams().do()

      const transaction = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
        sender: activeAddress,
        receiver: activeAddress,
        amount: 0,
        suggestedParams
      })

      atc.addTransaction({ txn: transaction, signer: transactionSigner })

      console.info(`[App] Sending transaction...`, transaction)

      setIsSending(true)

      const result = await atc.execute(algodClient, 4)

      console.info(`[App] ✅ Successfully sent transaction!`, {
        confirmedRound: result.confirmedRound,
        txIDs: result.txIDs
      })
    } catch (error) {
      console.error('[App] Error signing transaction:', error)
    } finally {
      setIsSending(false)
    }
  }

  const auth = async () => {
    if (!activeAddress) {
      throw new Error('[App] No active account')
    }
    try {
      const siwaRequest: Siwa = {
        domain: location.host,
        chain_id: '283',
        account_address: activeAddress,
        type: 'ed25519',
        uri: location.origin,
        version: '1',
        'issued-at': new Date().toISOString()
      }
      const dataString = canonify(siwaRequest)
      if (!dataString) throw Error('Invalid JSON')
      const data = btoa(dataString)
      const metadata = { scope: ScopeType.AUTH, encoding: 'base64' }
      const resp = await signData(data, metadata)
      // verify signature
      const enc = new TextEncoder()
      const clientDataJsonHash = await crypto.subtle.digest('SHA-256', enc.encode(dataString))
      const authenticatorDataHash = await crypto.subtle.digest('SHA-256', resp.authenticatorData)
      const toSign = new Uint8Array(64)
      toSign.set(new Uint8Array(clientDataJsonHash), 0)
      toSign.set(new Uint8Array(authenticatorDataHash), 32)
      const pubKey = algosdk.Address.fromString(activeAddress).publicKey
      if (!(await ed.verifyAsync(resp.signature, toSign, pubKey))) {
        throw new SignDataError('Verification Failed', 4300)
      }
      console.info(`[App] ✅ Successfully authenticated!`)
    } catch (error) {
      console.error('[App] Error signing data:', error)
    }
  }

  return (
    <div>
      <div className={styles.networkGroup}>
        <h4>
          Current Network: <span className={styles.activeNetwork}>{activeNetwork}</span>
        </h4>
        <div className={styles.networkButtons}>
          <button
            type="button"
            onClick={() => setActiveNetwork(NetworkId.BETANET)}
            disabled={activeNetwork === NetworkId.BETANET}
          >
            Set to Betanet
          </button>
          <button
            type="button"
            onClick={() => setActiveNetwork(NetworkId.TESTNET)}
            disabled={activeNetwork === NetworkId.TESTNET}
          >
            Set to Testnet
          </button>
          <button
            type="button"
            onClick={() => setActiveNetwork(NetworkId.MAINNET)}
            disabled={activeNetwork === NetworkId.MAINNET}
          >
            Set to Mainnet
          </button>
        </div>
      </div>

      {wallets.map((wallet) => (
        <div key={wallet.id} className={styles.walletGroup}>
          <h4 className={styles.walletName} data-active={wallet.isActive}>
            {wallet.metadata.name}
          </h4>
          <div className={styles.walletButtons}>
            <button
              type="button"
              onClick={() => handleConnect(wallet)}
              disabled={isConnectDisabled(wallet)}
            >
              Connect
            </button>
            <button
              type="button"
              onClick={() => wallet.disconnect()}
              disabled={!wallet.isConnected}
            >
              Disconnect
            </button>
            {wallet.isActive ? (
              <div className={styles.walletButtons}>
                <button type="button" onClick={sendTransaction} disabled={isSending}>
                  {isSending ? 'Sending Transaction...' : 'Send Transaction'}
                </button>
                {wallet.canSignData && (
                  <button type="button" onClick={auth}>
                    Authenticate
                  </button>
                )}
              </div>
            ) : (
              <button
                type="button"
                onClick={() => wallet.setActive()}
                disabled={!wallet.isConnected}
              >
                Set Active
              </button>
            )}
          </div>

          {isMagicLink(wallet) && (
            <div className={styles.inputGroup}>
              <label htmlFor="magic-email">Email:</label>
              <input
                id="magic-email"
                type="email"
                value={magicEmail}
                onChange={(e) => setMagicEmail(e.target.value)}
                placeholder="Enter email to connect..."
                disabled={wallet.isConnected}
              />
            </div>
          )}

          {/* Firebase SFA Authentication */}
          {isWeb3Auth(wallet) && isFirebaseConfigured && !wallet.isConnected && (
            <div className="firebase-sfa-section">
              <div className="section-divider">
                <span>or connect with Firebase</span>
              </div>
              {firebaseUser ? (
                <div className="firebase-user">
                  <span>Signed in as: {firebaseUser.email || firebaseUser.uid}</span>
                  <div className="firebase-user-buttons">
                    <button type="button" onClick={handleFirebaseSignOut}>
                      Sign Out
                    </button>
                    <button type="button" onClick={() => handleFirebaseConnect(wallet)}>
                      Connect with Firebase
                    </button>
                  </div>
                </div>
              ) : (
                <div className="firebase-auth">
                  <FirebaseAuth
                    onSignInSuccess={() => {
                      console.info('[App] Firebase sign-in successful')
                    }}
                  />
                </div>
              )}
            </div>
          )}
          {/* End Firebase SFA Authentication */}

          {wallet.isActive && wallet.accounts.length > 0 && (
            <div>
              <select onChange={(e) => setActiveAccount(e, wallet)}>
                {wallet.accounts.map((account) => (
                  <option key={account.address} value={account.address}>
                    {account.address}
                  </option>
                ))}
              </select>
            </div>
          )}
        </div>
      ))}
    </div>
  )
}
