// packages/use-wallet-solid/src/WalletProvider.tsx
import { WalletManager } from '@txnlab/use-wallet'
import { createContext, useContext, JSX, onMount } from 'solid-js'

interface WalletProviderProps {
  manager: WalletManager
  children: JSX.Element
}

const WalletContext = createContext<() => WalletManager>()

export const WalletProvider = (props: WalletProviderProps) => {
  const store = () => props.manager

  onMount(async () => {
    try {
      await props.manager.resumeSessions()
    } catch (error) {
      console.error('Error resuming sessions:', error)
    }
  })

  return <WalletContext.Provider value={store}>{props.children}</WalletContext.Provider>
}

export const useWalletManager = (): WalletManager => {
  const manager = useContext(WalletContext)
  if (!manager) {
    throw new Error('useWalletManager must be used within a WalletProvider')
  }
  return manager()
}

// packages/use-wallet-react/src/WalletProvider.tsx
'use client'

import { WalletManager } from '@txnlab/use-wallet-js'
import * as React from 'react'

const WalletContext = React.createContext<WalletManager | undefined>(undefined)

export const useWalletManager = () => {
  const manager = React.useContext(WalletContext)

  if (!manager) {
    throw new Error('useWallet must be used within the WalletProvider')
  }

  return manager
}

interface WalletProviderProps {
  manager: WalletManager
  children: React.ReactNode
}

export const WalletProvider = ({ manager, children }: WalletProviderProps): JSX.Element => {
  React.useEffect(() => {
    const resumeSessions = async () => {
      try {
        await manager.resumeSessions()
      } catch (error) {
        console.error('Error resuming sessions:', error)
      }
    }

    resumeSessions()
  }, [manager])

  return <WalletContext.Provider value={manager}>{children}</WalletContext.Provider>
}
