// examples/vue/src/App.vue
<script setup lang="ts">
import WalletList from './components/WalletList.vue'
import ActiveWallet from './components/ActiveWallet.vue'
import NetworkSwitch from './components/NetworkSwitch.vue'
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <header class="border-b border-gray-200 bg-white">
      <div class="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
        <h1 class="text-lg font-semibold tracking-tight text-gray-900">
          use-wallet<span class="text-gray-400 font-normal"> / vue</span>
        </h1>
        <NetworkSwitch />
      </div>
    </header>
    <main class="mx-auto max-w-5xl px-6 py-8">
      <div class="grid gap-8 lg:grid-cols-[320px_1fr]">
        <WalletList />
        <ActiveWallet />
      </div>
    </main>
  </div>
</template>

// examples/react/src/App.tsx
import { WalletManager, WalletProvider } from '@txnlab/use-wallet-react'
import { defly } from '@txnlab/use-wallet-defly'
import { exodus } from '@txnlab/use-wallet-exodus'
import { kibisis } from '@txnlab/use-wallet-kibisis'
import { kmd } from '@txnlab/use-wallet-kmd'
import { lute } from '@txnlab/use-wallet-lute'
import { mnemonic } from '@txnlab/use-wallet-mnemonic'
import { pera } from '@txnlab/use-wallet-pera'
import { w3wallet } from '@txnlab/use-wallet-w3wallet'
import { walletConnect } from '@txnlab/use-wallet-walletconnect'
import { web3auth } from '@txnlab/use-wallet-web3auth'
import { WalletList } from './WalletList.tsx'
import { ActiveWallet } from './ActiveWallet.tsx'
import { NetworkSwitch } from './NetworkSwitch.tsx'

const WC_PROJECT_ID = 'fcfde0713d43baa0d23be0773c80a72b'

const wallets = [
  pera(),
  lute(),
  defly(),
  exodus(),
  walletConnect({ projectId: WC_PROJECT_ID }),
  walletConnect({ projectId: WC_PROJECT_ID, skin: 'biatec' }),
  kibisis(),
  w3wallet(),
  kmd(),
  mnemonic(),
  ...(import.meta.env.VITE_WEB3AUTH_CLIENT_ID
    ? [web3auth({ clientId: import.meta.env.VITE_WEB3AUTH_CLIENT_ID })]
    : [])
]

const walletManager = new WalletManager({
  wallets,
  defaultNetwork: 'testnet'
})

function App() {
  return (
    <WalletProvider manager={walletManager}>
      <div className="min-h-screen bg-gray-50">
        <header className="border-b border-gray-200 bg-white">
          <div className="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
            <h1 className="text-lg font-semibold tracking-tight text-gray-900">
              use-wallet<span className="text-gray-400 font-normal"> / react</span>
            </h1>
            <NetworkSwitch />
          </div>
        </header>
        <main className="mx-auto max-w-5xl px-6 py-8">
          <div className="grid gap-8 lg:grid-cols-[320px_1fr]">
            <WalletList />
            <ActiveWallet />
          </div>
        </main>
      </div>
    </WalletProvider>
  )
}

export default App
